name: 'Prepare'
description: 'Move and prepare packages for upload to S3.'
inputs:
  working_dir:
    description: 'Working directory path containing packages.'
    required: true
outputs:
  archive_dir:
    description: 'Directory with Packages to be archived.'
  destination:
    description: 'S3 destination to upload to.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.working_dir }}
